---
- hosts: all
  ignore_errors: yes
  tasks: 
    - lvol: 
        lv: data
        vg: research 
        size: '1500'
    - debug: 
        msg: 'VG not found'
      when: ansible_lvm.vgs.research is not defined
    - debug: 
        msg: 'LV can not be created with the following size'
      when: ansible_lvm.vgs.research.size_g < '1500'
    - lvol: 
        lv: data
        vg: research 
        size: '800'
      when: ansible_lvm.vgs.research.size_g < '1500'
    - filesystem: 
        fstype: ext4
        dev: /dev/research/data
