---
- hosts: dev,test,prod
  tasks: 
    - yum:
        name:
          - php
          - mariadb
        state: present
    - yum:
        name: '@Development Tools'
        state: present
      when: inventory_hostname in groups['dev']
    - yum:
        name: '*'
        state: latest
      when: inventory_hostname in groups['dev']
